services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080

  backend:
    build: ./backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      # ✅ Wait script variables (renamed to avoid shell conflict)
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306

      # ✅ Spring Boot DB configuration
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: ecomuser
      SPRING_DATASOURCE_PASSWORD: ecompass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

    networks:
      - backend-network

    entrypoint: >
      sh -c "
        echo '⏳ Waiting for MySQL to be ready...';
        until nc -z mysql 3306; do
          echo '⏱️  Still waiting for MySQL at mysql:3306...';
          sleep 2;
        done;
        echo '✅ MySQL is up - starting Spring Boot app';
        java -jar /app/app.jar
      "


  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecomuser
      MYSQL_PASSWORD: ecompass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network

volumes:
  mysql-data:

networks:
  backend-network:
